### ISSUE TITLE
Fixes to older version documentation 

### ISSUE THREAD

**Issue by moxiegirl** [docker/docs.docker.com#35]
The older versions of documentation are broken.  Currently, they are being served off of: http://beta-docs.docker.io/v1.6/

* [ ] Backup the folders on docs.docker.com to me sure we have a copy
* [ ] Manipulate the existing files so that they work from the folders where they reside

**Comment by kytrinyx** [comment]
This looks fixed to me.

When I go to https://docs.docker.com/ and click on _docs archive_ in the sidebar, I'm able to navigate to each of the previous versions listed.

**Comment by moxiegirl** [comment]
@kytrinyx You are correct. This was fixed. Thanks for the ping I'll close this.
