### ISSUE TITLE
Links to examples don't work

### ISSUE THREAD

**Issue by wkoszek** [docker/docs.docker.com#45]
https://docs.docker.com/examples/

Only the last one works. Others point to .md files. If you remove .md extension, it works OK:

https://docs.docker.com/examples/mongodb.md
https://docs.docker.com/examples/mongodb

**Comment by aditirajagopal** [comment]
ping @wkoszek - looks like the all links on https://docs.docker.com/examples/ work. Can you please verify?

**Comment by wkoszek** [comment]
@aditirajagopal Looks like it's fixed now.
