### ISSUE TITLE
Remote API version listing is not incremental 

### ISSUE THREAD

**Issue by tahaozket** [docker/docs.docker.com#54]
https://docs.docker.com/reference/api/docker_remote_api/

![image](https://cloud.githubusercontent.com/assets/668860/10025840/2b075478-6113-11e5-8b6c-b07477b1e507.png)

**Comment by thaJeztah** [comment]
Thanks for reporting! I *think* this was fixed, but not yet published, I'll check and comment here

**Comment by moxiegirl** [comment]
Moved to: https://github.com/docker/docker/issues/18440
