### ISSUE TITLE
Add docker-elements onto the remote API Client Libraries

### ISSUE THREAD

**Issue by jwayong** [docker/docs.docker.com#55]
Please add docker-elements on the remote API Client Libraries page https://docs.docker.com/reference/api/remote_api_client_libraries/

Name: docker-elements
Language/Framework: HTML5/JavaScripts (Polymer Web Components)
Link: https://github.com/kapalhq/docker-elements 

These elements are reusable HTML WebComponents that can be reused in HTML5 app or even in Server-Side WebApp

**Comment by thaJeztah** [comment]
Thanks for the suggestion @jwayong! Would you be interested in contributing, and creating a pull request for that? The file that's used for generating that part of the documentation can be found in the main "docker" repo, here: https://github.com/docker/docker/blob/master/docs/reference/api/remote_api_client_libraries.md

We have a "contribution guide" explaining how our contribution workflow works; https://docs.docker.com/project/make-a-contribution/

Let us know if you're interested! If you need help, feel free to hop in the #docker-dev IRC channel on freenode :+1:

**Comment by jwayong** [comment]
Thanks @thaJeztah, i will close this issue and follow the workflow on the main docker repo.

**Comment by thaJeztah** [comment]
Thanks @jwayong !
