### ISSUE TITLE
Better handling of 404's

### ISSUE THREAD

**Issue by thaJeztah** [docker/docs.docker.com#56]
I just came on a 404 checking if we still had 1.7 docs, and thought I should open an issue for that;

404 pages currently are not very pleasant to look at;
https://docs.docker.com/v1.7/registry/spec/json/

<img width="804" alt="screen shot 2015-10-09 at 17 53 40" src="https://cloud.githubusercontent.com/assets/1804568/10398690/bdc27164-6eae-11e5-9213-d315c8c9c916.png">

**Comment by dnephin** [comment]
Related to https://github.com/docker/docs-base/issues/155 I believe

**Comment by thaJeztah** [comment]
@dnephin ah! yes, I saw that one come by. I'll close this one if we're tracking it there
