### ISSUE TITLE
Code styling missing from output

### ISSUE THREAD

**Issue by J3RN** [docker/docs.docker.com#68]
On [http://docs.docker.com/mac/step_one/](http://docs.docker.com/mac/step_one/), I found a section where it looks like that output was supposed to be formatted as code, but wasn't.

Using Firefox 42 on OS X.

<img width="930" alt="screen shot 2015-11-03 at 23 43 30" src="https://cloud.githubusercontent.com/assets/2058614/10929700/db2c6932-8284-11e5-88cf-fc654048a21d.png">

**Comment by aditirajagopal** [comment]
Can you please verify that this is still an issue? Looks like it works.

**Comment by thaJeztah** [comment]
this is fixed in https://github.com/docker/tutorials/pull/55 thanks for reporting @J3RN (and thanks for checking, @aditirajagopal!)

I'll close this issue because this has been resolved
