### ISSUE TITLE
Add rx-docker-client to docker library implementations

### ISSUE THREAD

**Issue by shekhargulati** [docker/docs.docker.com#71]
Can you please add https://github.com/shekhargulati/rx-docker-client to http://docs.docker.com/engine/reference/api/remote_api_client_libraries/?

**Comment by thaJeztah** [comment]
@shekhargulati that page is part of the docker documentation, which is located in another repository, here; https://github.com/docker/docker/blob/master/docs/reference/api/remote_api_client_libraries.md

Are you interested in creating a pull request to add the library?

**Comment by thaJeztah** [comment]
PR is opened here https://github.com/docker/docker/pull/17866

**Comment by thaJeztah** [comment]
I'm going to close this issue because there's a PR to fix this. Thanks @shekhargulati
