### ISSUE TITLE
docs.docker.com doesn't enforce secure connection (HSTS)

### ISSUE THREAD

**Issue by thaJeztah** [docker/docs.docker.com#86]
moved from https://github.com/docker/docker/issues/12498 look for more information there

The docs website is accessible via http://docs.docker.com and doesn't automatically redirect to https://docs.docker.com

Given that the site is accessible via `https://`, I think it should enforce a secure connection.

**Comment by xbglowx** [comment]
I just updated the cloudfront config to force the redirection from http -> https.

**Comment by thaJeztah** [comment]
Thank you @xbglowx! I'll close this issue. Happy :)
